workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'  # 只有通过 schedule 触发才执行
      when: always
    - when: never  # 其他所有情况都不执行

stages:
  - build

before_script:
  # 所有作业执行前运行的脚本
  - echo "Setting up the environment"
  - export PATH=/home/lb/projects/gitlab-ci/drmhwc2-configs/build_sh/:$PATH
  - echo "Updated PATH=$PATH"  # 打印修改后的 PATH

a15_build:
  stage: build
  tags:
    - android-15
  script:
    - echo "Building the Android-15 SDK ..."
    - . 15_build_drmhwc2.sh

a14_build:
  stage: build
  tags:
    - android-14
  script:
    - echo "Building the Android-14 SDK ..."
    - . 14_build_drmhwc2.sh

a13_build:
  stage: build
  tags:
    - android-13
  script:
    - echo "Building the Android-14 SDK ..."
    - . 13_build_drmhwc2.sh

a12_build:
  stage: build
  tags:
    - android-12
  script:
    - echo "Building the Android-14 SDK ..."
    - . 12_build_drmhwc2.sh

a11_build:
  stage: build
  tags:
    - android-11
  script:
    - echo "Building the Android-14 SDK ..."
    - . 11_build_drmhwc2.sh